CREATE TABLE `new_auth_group_sourth` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Id',
  `auth_no` varchar(45) NOT NULL DEFAULT '' COMMENT '授权编号',
  `auth_type` int(11) NOT NULL DEFAULT '5' COMMENT '授权类型',
  `sday` datetime NOT NULL COMMENT '生效日期',
  `eday` datetime NOT NULL COMMENT '截止日期',
  `time_range` varchar(45) NOT NULL DEFAULT '00:00:00,23:59:59' COMMENT '时间段',
  `week` varchar(45) NOT NULL DEFAULT '0,1,2,3,4,5,6' COMMENT '一周的哪天0代表周一,6代表周日',
  `is_share` tinyint(1) NOT NULL DEFAULT '0' COMMENT '车位是否共享',
  `share_tol` int(10) DEFAULT '0' COMMENT '共享车位数',
  `holder_name` varchar(30) NOT NULL DEFAULT '' COMMENT '持有人',
  `phone` varchar(30) DEFAULT '' COMMENT '电话',
  `address` varchar(255) DEFAULT '' COMMENT '地址',
  `email` varchar(255) DEFAULT '' COMMENT '邮箱',
  `remarks` varchar(255) DEFAULT '' COMMENT '备注',
  `valid_flag` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否过期:0:未过期，1：已过期',
  `nested` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0:外层1:内层',
  `msg_json` varchar(225) DEFAULT '' COMMENT '预留json',
  `serial_no` varchar(45) DEFAULT '' COMMENT '平台授权时的序列号',
  `register` varchar(45) DEFAULT '' COMMENT '操作人',
  `op_type` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '操作类型1:添加组2:编辑组3:删除组4:充值组5:扣费组6:添加车牌7:编辑车牌8:删除车牌9:更新车位10:添加车位编号11:编辑车位编号12:删除车位编号',
  `op_time` datetime NOT NULL COMMENT '操作时间',
  `save_time` datetime NOT NULL COMMENT '保存时间',
  `depot_id` int(11) NOT NULL DEFAULT '0' COMMENT '车场id',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5056 DEFAULT CHARSET=utf8 COMMENT='新授权组';

CREATE TABLE `new_auth_group_north` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Id',
  `auth_no` varchar(45) NOT NULL DEFAULT '' COMMENT '授权编号',
  `auth_type` int(11) NOT NULL DEFAULT '5' COMMENT '授权类型',
  `sday` datetime NOT NULL COMMENT '生效日期',
  `eday` datetime NOT NULL COMMENT '截止日期',
  `time_range` varchar(45) NOT NULL DEFAULT '00:00:00,23:59:59' COMMENT '时间段',
  `week` varchar(45) NOT NULL DEFAULT '0,1,2,3,4,5,6' COMMENT '一周的哪天0代表周一,6代表周日',
  `is_share` tinyint(1) NOT NULL DEFAULT '0' COMMENT '车位是否共享',
  `share_tol` int(10) DEFAULT '0' COMMENT '共享车位数',
  `holder_name` varchar(30) NOT NULL DEFAULT '' COMMENT '持有人',
  `phone` varchar(30) DEFAULT '' COMMENT '电话',
  `address` varchar(255) DEFAULT '' COMMENT '地址',
  `email` varchar(255) DEFAULT '' COMMENT '邮箱',
  `remarks` varchar(255) DEFAULT '' COMMENT '备注',
  `valid_flag` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否过期:0:未过期，1：已过期',
  `nested` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0:外层1:内层',
  `msg_json` varchar(225) DEFAULT '' COMMENT '预留json',
  `serial_no` varchar(45) DEFAULT '' COMMENT '平台授权时的序列号',
  `register` varchar(45) DEFAULT '' COMMENT '操作人',
  `op_type` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '操作类型1:添加组2:编辑组3:删除组4:充值组5:扣费组6:添加车牌7:编辑车牌8:删除车牌9:更新车位10:添加车位编号11:编辑车位编号12:删除车位编号',
  `op_time` datetime NOT NULL COMMENT '操作时间',
  `save_time` datetime NOT NULL COMMENT '保存时间',
  `depot_id` int(11) NOT NULL DEFAULT '0' COMMENT '车场id',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5056 DEFAULT CHARSET=utf8 COMMENT='新授权组';

CREATE TABLE `new_auth_group_employees` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Id',
  `auth_no` varchar(45) NOT NULL DEFAULT '' COMMENT '授权编号',
  `auth_type` int(11) NOT NULL DEFAULT '5' COMMENT '授权类型',
  `sday` datetime NOT NULL COMMENT '生效日期',
  `eday` datetime NOT NULL COMMENT '截止日期',
  `time_range` varchar(45) NOT NULL DEFAULT '00:00:00,23:59:59' COMMENT '时间段',
  `week` varchar(45) NOT NULL DEFAULT '0,1,2,3,4,5,6' COMMENT '一周的哪天0代表周一,6代表周日',
  `is_share` tinyint(1) NOT NULL DEFAULT '0' COMMENT '车位是否共享',
  `share_tol` int(10) DEFAULT '0' COMMENT '共享车位数',
  `holder_name` varchar(30) NOT NULL DEFAULT '' COMMENT '持有人',
  `phone` varchar(30) DEFAULT '' COMMENT '电话',
  `address` varchar(255) DEFAULT '' COMMENT '地址',
  `email` varchar(255) DEFAULT '' COMMENT '邮箱',
  `remarks` varchar(255) DEFAULT '' COMMENT '备注',
  `valid_flag` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否过期:0:未过期，1：已过期',
  `nested` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0:外层1:内层',
  `msg_json` varchar(225) DEFAULT '' COMMENT '预留json',
  `serial_no` varchar(45) DEFAULT '' COMMENT '平台授权时的序列号',
  `register` varchar(45) DEFAULT '' COMMENT '操作人',
  `op_type` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '操作类型1:添加组2:编辑组3:删除组4:充值组5:扣费组6:添加车牌7:编辑车牌8:删除车牌9:更新车位10:添加车位编号11:编辑车位编号12:删除车位编号',
  `op_time` datetime NOT NULL COMMENT '操作时间',
  `save_time` datetime NOT NULL COMMENT '保存时间',
  `depot_id` int(11) NOT NULL DEFAULT '0' COMMENT '车场id',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5056 DEFAULT CHARSET=utf8 COMMENT='新授权组';
