CREATE TABLE `new_auth_share_sourth` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Id',
  `auth_no` varchar(45) NOT NULL DEFAULT '' COMMENT '授权编号',
  `vpr_plate` varchar(25) DEFAULT '' COMMENT '车牌号',
  `vpr_plate_noword` varchar(25) NOT NULL DEFAULT '' COMMENT '不带汉字车牌',
  `vpr_card` varchar(20) DEFAULT '' COMMENT '卡号',
  `remark` varchar(200) DEFAULT '' COMMENT '备注',
  `is_occupied` tinyint(1) NOT NULL DEFAULT '0' COMMENT '占用标志',
  `is_in` tinyint(1) NOT NULL DEFAULT '0' COMMENT '场内标志',
  `in_time` datetime NOT NULL COMMENT '进场时间',
  `auth_takeeffect_time` datetime NOT NULL COMMENT '授权生效时间',
  `serial_no` varchar(45) DEFAULT '' COMMENT '平台授权时的序列号',
  `register` varchar(45) DEFAULT NULL COMMENT '操作人',
  `op_type` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '操作类型1:添加组2:编辑组3:删除组4:充值组5:扣费组6:添加车牌7:编辑车牌8:删除车牌9:车位占用10:添加车位编号11:编辑车位编号12:删除车位编号',
  `op_time` datetime NOT NULL COMMENT '操作时间',
  `save_time` datetime NOT NULL COMMENT '保存时间',
  `depot_id` int(11) NOT NULL DEFAULT '0' COMMENT '车场id',
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_index` (`auth_no`,`vpr_plate`,`vpr_card`,`depot_id`) USING BTREE,
  KEY `auth_no` (`auth_no`) USING BTREE,
  KEY `vpr_plate_noword` (`vpr_plate_noword`)
) ENGINE=InnoDB AUTO_INCREMENT=5059 DEFAULT CHARSET=utf8 COMMENT='车牌表';

CREATE TABLE `new_auth_share_employees` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Id',
  `auth_no` varchar(45) NOT NULL DEFAULT '' COMMENT '授权编号',
  `vpr_plate` varchar(25) DEFAULT '' COMMENT '车牌号',
  `vpr_plate_noword` varchar(25) NOT NULL DEFAULT '' COMMENT '不带汉字车牌',
  `vpr_card` varchar(20) DEFAULT '' COMMENT '卡号',
  `remark` varchar(200) DEFAULT '' COMMENT '备注',
  `is_occupied` tinyint(1) NOT NULL DEFAULT '0' COMMENT '占用标志',
  `is_in` tinyint(1) NOT NULL DEFAULT '0' COMMENT '场内标志',
  `in_time` datetime NOT NULL COMMENT '进场时间',
  `auth_takeeffect_time` datetime NOT NULL COMMENT '授权生效时间',
  `serial_no` varchar(45) DEFAULT '' COMMENT '平台授权时的序列号',
  `register` varchar(45) DEFAULT NULL COMMENT '操作人',
  `op_type` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '操作类型1:添加组2:编辑组3:删除组4:充值组5:扣费组6:添加车牌7:编辑车牌8:删除车牌9:车位占用10:添加车位编号11:编辑车位编号12:删除车位编号',
  `op_time` datetime NOT NULL COMMENT '操作时间',
  `save_time` datetime NOT NULL COMMENT '保存时间',
  `depot_id` int(11) NOT NULL DEFAULT '0' COMMENT '车场id',
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_index` (`auth_no`,`vpr_plate`,`vpr_card`,`depot_id`) USING BTREE,
  KEY `auth_no` (`auth_no`) USING BTREE,
  KEY `vpr_plate_noword` (`vpr_plate_noword`)
) ENGINE=InnoDB AUTO_INCREMENT=5059 DEFAULT CHARSET=utf8 COMMENT='车牌表';

CREATE TABLE `new_auth_share_north` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Id',
  `auth_no` varchar(45) NOT NULL DEFAULT '' COMMENT '授权编号',
  `vpr_plate` varchar(25) DEFAULT '' COMMENT '车牌号',
  `vpr_plate_noword` varchar(25) NOT NULL DEFAULT '' COMMENT '不带汉字车牌',
  `vpr_card` varchar(20) DEFAULT '' COMMENT '卡号',
  `remark` varchar(200) DEFAULT '' COMMENT '备注',
  `is_occupied` tinyint(1) NOT NULL DEFAULT '0' COMMENT '占用标志',
  `is_in` tinyint(1) NOT NULL DEFAULT '0' COMMENT '场内标志',
  `in_time` datetime NOT NULL COMMENT '进场时间',
  `auth_takeeffect_time` datetime NOT NULL COMMENT '授权生效时间',
  `serial_no` varchar(45) DEFAULT '' COMMENT '平台授权时的序列号',
  `register` varchar(45) DEFAULT NULL COMMENT '操作人',
  `op_type` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '操作类型1:添加组2:编辑组3:删除组4:充值组5:扣费组6:添加车牌7:编辑车牌8:删除车牌9:车位占用10:添加车位编号11:编辑车位编号12:删除车位编号',
  `op_time` datetime NOT NULL COMMENT '操作时间',
  `save_time` datetime NOT NULL COMMENT '保存时间',
  `depot_id` int(11) NOT NULL DEFAULT '0' COMMENT '车场id',
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_index` (`auth_no`,`vpr_plate`,`vpr_card`,`depot_id`) USING BTREE,
  KEY `auth_no` (`auth_no`) USING BTREE,
  KEY `vpr_plate_noword` (`vpr_plate_noword`)
) ENGINE=InnoDB AUTO_INCREMENT=5059 DEFAULT CHARSET=utf8 COMMENT='车牌表';
