CREATE TABLE `records_inout_sourth` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Id',
  `trace_uk` varchar(45) NOT NULL DEFAULT '' COMMENT '轨迹标识',
  `in_time` datetime DEFAULT NULL COMMENT '进场时间',
  `in_vpr_card` varchar(20) DEFAULT '' COMMENT '卡号',
  `in_vpr_plate` varchar(25) DEFAULT '' COMMENT '车牌号',
  `in_vpr_plate_color` int(11) DEFAULT NULL COMMENT '车牌颜色',
  `in_vpr_pic_full` varchar(255) DEFAULT '' COMMENT '车辆全图',
  `in_vpr_pic_plate` varchar(255) DEFAULT '' COMMENT '车牌图片',
  `in_vpr_plate_slave` varchar(25) DEFAULT '' COMMENT '从车牌号',
  `in_vpr_pic_full_slave` varchar(255) NOT NULL DEFAULT '' COMMENT '从识别仪全图',
  `in_vpr_pic_plate_slave` varchar(255) NOT NULL DEFAULT '' COMMENT '从识别仪车牌图',
  `in_vpr_plate_color_slave` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '从识别仪颜色',
  `in_used_plate` varchar(25) DEFAULT '' COMMENT '入场使用车牌',
  `in_used_plate_color` int(11) NOT NULL DEFAULT '0' COMMENT '使用的车牌颜色',
  `in_depot_id` int(11) DEFAULT NULL COMMENT '车场Id',
  `in_site_name` varchar(20) DEFAULT '' COMMENT '入口名称',
  `in_auth_type` int(11) DEFAULT '0' COMMENT '授权类型',
  `in_state_details` text COMMENT '进场情况说明包括授权信息',
  `in_state` int(11) NOT NULL DEFAULT '0' COMMENT '进场状态(0, 未进车;1, 自动抬杆;2, 无牌车;3, 手动开闸；4：造的数据)',
  `in_operate_time` datetime NOT NULL COMMENT '操作时间',
  `in_operator` varchar(30) DEFAULT '' COMMENT '操作人',
  `out_vpr_plate` varchar(25) NOT NULL DEFAULT '' COMMENT '车牌号',
  `out_vpr_card` varchar(20) NOT NULL DEFAULT '' COMMENT '卡号',
  `out_time` datetime NOT NULL COMMENT '出车时间',
  `out_vpr_plate_color` int(11) NOT NULL COMMENT '车牌颜色',
  `out_vpr_pic_full` varchar(255) NOT NULL DEFAULT '',
  `out_vpr_pic_plate` varchar(255) NOT NULL DEFAULT '',
  `out_vpr_plate_slave` varchar(25) DEFAULT '' COMMENT '从车牌号',
  `out_vpr_pic_full_slave` varchar(255) NOT NULL DEFAULT '' COMMENT '从识别仪全图',
  `out_vpr_pic_plate_slave` varchar(255) NOT NULL DEFAULT '' COMMENT '从识别仪车牌图',
  `out_vpr_plate_color_slave` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '从识别仪颜色',
  `out_used_plate` varchar(25) DEFAULT '' COMMENT '出场使用车牌',
  `out_depot_id` int(11) DEFAULT NULL COMMENT '车场id',
  `out_site_name` varchar(20) DEFAULT '' COMMENT '出入口名称',
  `out_auth_type` int(11) DEFAULT '0' COMMENT '授权类型',
  `out_state_details` text COMMENT '出车情况说明(包含授权信息)',
  `out_state` int(11) NOT NULL DEFAULT '0' COMMENT '出场状态',
  `out_stopping_time` int(11) NOT NULL COMMENT '停车时长',
  `out_should_pay` int(11) NOT NULL COMMENT '出场时还应收',
  `out_remarks` text COMMENT '备注',
  `out_operate_time` datetime NOT NULL COMMENT '备注',
  `out_operator` varchar(30) DEFAULT '' COMMENT '操作人',
  `out_open_time` datetime DEFAULT NULL COMMENT '出车放行时间',
  `out_total_price` int(11) DEFAULT '0' COMMENT '总金额',
  `self_depot_fee` int(11) NOT NULL DEFAULT '0' COMMENT '本车场费用',
  `vehicle_type` int(11) DEFAULT '1' COMMENT '车型：小车1，大车2，军警车65534',
  `power_type` int(11) DEFAULT '1' COMMENT '普通1，混合动力2，纯电动3',
  `logo` varchar(25) DEFAULT '未知' COMMENT '车标',
  `vehicle_model` int(11) DEFAULT '1' COMMENT '车运营类型',
  `body_color` int(11) DEFAULT '0' COMMENT '车身颜色',
  `in_taxprinted` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '已开具发票(0:未开,1:已开)',
  `taxprinted` tinyint(4) DEFAULT '0' COMMENT '已开具发票(0:未开,1:已开)',
  `now_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `out_time` (`out_time`),
  KEY `now_time` (`now_time`),
  KEY `plate` (`in_used_plate`),
  KEY `card` (`in_vpr_card`),
  KEY `trace_uk` (`trace_uk`) USING BTREE,
  KEY `in_time` (`in_time`)
) ENGINE=InnoDB AUTO_INCREMENT=133432 DEFAULT CHARSET=utf8;

CREATE TABLE `records_inout_north` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Id',
  `trace_uk` varchar(45) NOT NULL DEFAULT '' COMMENT '轨迹标识',
  `in_time` datetime DEFAULT NULL COMMENT '进场时间',
  `in_vpr_card` varchar(20) DEFAULT '' COMMENT '卡号',
  `in_vpr_plate` varchar(25) DEFAULT '' COMMENT '车牌号',
  `in_vpr_plate_color` int(11) DEFAULT NULL COMMENT '车牌颜色',
  `in_vpr_pic_full` varchar(255) DEFAULT '' COMMENT '车辆全图',
  `in_vpr_pic_plate` varchar(255) DEFAULT '' COMMENT '车牌图片',
  `in_vpr_plate_slave` varchar(25) DEFAULT '' COMMENT '从车牌号',
  `in_vpr_pic_full_slave` varchar(255) NOT NULL DEFAULT '' COMMENT '从识别仪全图',
  `in_vpr_pic_plate_slave` varchar(255) NOT NULL DEFAULT '' COMMENT '从识别仪车牌图',
  `in_vpr_plate_color_slave` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '从识别仪颜色',
  `in_used_plate` varchar(25) DEFAULT '' COMMENT '入场使用车牌',
  `in_used_plate_color` int(11) NOT NULL DEFAULT '0' COMMENT '使用的车牌颜色',
  `in_depot_id` int(11) DEFAULT NULL COMMENT '车场Id',
  `in_site_name` varchar(20) DEFAULT '' COMMENT '入口名称',
  `in_auth_type` int(11) DEFAULT '0' COMMENT '授权类型',
  `in_state_details` text COMMENT '进场情况说明包括授权信息',
  `in_state` int(11) NOT NULL DEFAULT '0' COMMENT '进场状态(0, 未进车;1, 自动抬杆;2, 无牌车;3, 手动开闸；4：造的数据)',
  `in_operate_time` datetime NOT NULL COMMENT '操作时间',
  `in_operator` varchar(30) DEFAULT '' COMMENT '操作人',
  `out_vpr_plate` varchar(25) NOT NULL DEFAULT '' COMMENT '车牌号',
  `out_vpr_card` varchar(20) NOT NULL DEFAULT '' COMMENT '卡号',
  `out_time` datetime NOT NULL COMMENT '出车时间',
  `out_vpr_plate_color` int(11) NOT NULL COMMENT '车牌颜色',
  `out_vpr_pic_full` varchar(255) NOT NULL DEFAULT '',
  `out_vpr_pic_plate` varchar(255) NOT NULL DEFAULT '',
  `out_vpr_plate_slave` varchar(25) DEFAULT '' COMMENT '从车牌号',
  `out_vpr_pic_full_slave` varchar(255) NOT NULL DEFAULT '' COMMENT '从识别仪全图',
  `out_vpr_pic_plate_slave` varchar(255) NOT NULL DEFAULT '' COMMENT '从识别仪车牌图',
  `out_vpr_plate_color_slave` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '从识别仪颜色',
  `out_used_plate` varchar(25) DEFAULT '' COMMENT '出场使用车牌',
  `out_depot_id` int(11) DEFAULT NULL COMMENT '车场id',
  `out_site_name` varchar(20) DEFAULT '' COMMENT '出入口名称',
  `out_auth_type` int(11) DEFAULT '0' COMMENT '授权类型',
  `out_state_details` text COMMENT '出车情况说明(包含授权信息)',
  `out_state` int(11) NOT NULL DEFAULT '0' COMMENT '出场状态',
  `out_stopping_time` int(11) NOT NULL COMMENT '停车时长',
  `out_should_pay` int(11) NOT NULL COMMENT '出场时还应收',
  `out_remarks` text COMMENT '备注',
  `out_operate_time` datetime NOT NULL COMMENT '备注',
  `out_operator` varchar(30) DEFAULT '' COMMENT '操作人',
  `out_open_time` datetime DEFAULT NULL COMMENT '出车放行时间',
  `out_total_price` int(11) DEFAULT '0' COMMENT '总金额',
  `self_depot_fee` int(11) NOT NULL DEFAULT '0' COMMENT '本车场费用',
  `vehicle_type` int(11) DEFAULT '1' COMMENT '车型：小车1，大车2，军警车65534',
  `power_type` int(11) DEFAULT '1' COMMENT '普通1，混合动力2，纯电动3',
  `logo` varchar(25) DEFAULT '未知' COMMENT '车标',
  `vehicle_model` int(11) DEFAULT '1' COMMENT '车运营类型',
  `body_color` int(11) DEFAULT '0' COMMENT '车身颜色',
  `in_taxprinted` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '已开具发票(0:未开,1:已开)',
  `taxprinted` tinyint(4) DEFAULT '0' COMMENT '已开具发票(0:未开,1:已开)',
  `now_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `out_time` (`out_time`),
  KEY `now_time` (`now_time`),
  KEY `plate` (`in_used_plate`),
  KEY `card` (`in_vpr_card`),
  KEY `trace_uk` (`trace_uk`) USING BTREE,
  KEY `in_time` (`in_time`)
) ENGINE=InnoDB AUTO_INCREMENT=133432 DEFAULT CHARSET=utf8;

CREATE TABLE `records_inout_employees` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Id',
  `trace_uk` varchar(45) NOT NULL DEFAULT '' COMMENT '轨迹标识',
  `in_time` datetime DEFAULT NULL COMMENT '进场时间',
  `in_vpr_card` varchar(20) DEFAULT '' COMMENT '卡号',
  `in_vpr_plate` varchar(25) DEFAULT '' COMMENT '车牌号',
  `in_vpr_plate_color` int(11) DEFAULT NULL COMMENT '车牌颜色',
  `in_vpr_pic_full` varchar(255) DEFAULT '' COMMENT '车辆全图',
  `in_vpr_pic_plate` varchar(255) DEFAULT '' COMMENT '车牌图片',
  `in_vpr_plate_slave` varchar(25) DEFAULT '' COMMENT '从车牌号',
  `in_vpr_pic_full_slave` varchar(255) NOT NULL DEFAULT '' COMMENT '从识别仪全图',
  `in_vpr_pic_plate_slave` varchar(255) NOT NULL DEFAULT '' COMMENT '从识别仪车牌图',
  `in_vpr_plate_color_slave` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '从识别仪颜色',
  `in_used_plate` varchar(25) DEFAULT '' COMMENT '入场使用车牌',
  `in_used_plate_color` int(11) NOT NULL DEFAULT '0' COMMENT '使用的车牌颜色',
  `in_depot_id` int(11) DEFAULT NULL COMMENT '车场Id',
  `in_site_name` varchar(20) DEFAULT '' COMMENT '入口名称',
  `in_auth_type` int(11) DEFAULT '0' COMMENT '授权类型',
  `in_state_details` text COMMENT '进场情况说明包括授权信息',
  `in_state` int(11) NOT NULL DEFAULT '0' COMMENT '进场状态(0, 未进车;1, 自动抬杆;2, 无牌车;3, 手动开闸；4：造的数据)',
  `in_operate_time` datetime NOT NULL COMMENT '操作时间',
  `in_operator` varchar(30) DEFAULT '' COMMENT '操作人',
  `out_vpr_plate` varchar(25) NOT NULL DEFAULT '' COMMENT '车牌号',
  `out_vpr_card` varchar(20) NOT NULL DEFAULT '' COMMENT '卡号',
  `out_time` datetime NOT NULL COMMENT '出车时间',
  `out_vpr_plate_color` int(11) NOT NULL COMMENT '车牌颜色',
  `out_vpr_pic_full` varchar(255) NOT NULL DEFAULT '',
  `out_vpr_pic_plate` varchar(255) NOT NULL DEFAULT '',
  `out_vpr_plate_slave` varchar(25) DEFAULT '' COMMENT '从车牌号',
  `out_vpr_pic_full_slave` varchar(255) NOT NULL DEFAULT '' COMMENT '从识别仪全图',
  `out_vpr_pic_plate_slave` varchar(255) NOT NULL DEFAULT '' COMMENT '从识别仪车牌图',
  `out_vpr_plate_color_slave` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '从识别仪颜色',
  `out_used_plate` varchar(25) DEFAULT '' COMMENT '出场使用车牌',
  `out_depot_id` int(11) DEFAULT NULL COMMENT '车场id',
  `out_site_name` varchar(20) DEFAULT '' COMMENT '出入口名称',
  `out_auth_type` int(11) DEFAULT '0' COMMENT '授权类型',
  `out_state_details` text COMMENT '出车情况说明(包含授权信息)',
  `out_state` int(11) NOT NULL DEFAULT '0' COMMENT '出场状态',
  `out_stopping_time` int(11) NOT NULL COMMENT '停车时长',
  `out_should_pay` int(11) NOT NULL COMMENT '出场时还应收',
  `out_remarks` text COMMENT '备注',
  `out_operate_time` datetime NOT NULL COMMENT '备注',
  `out_operator` varchar(30) DEFAULT '' COMMENT '操作人',
  `out_open_time` datetime DEFAULT NULL COMMENT '出车放行时间',
  `out_total_price` int(11) DEFAULT '0' COMMENT '总金额',
  `self_depot_fee` int(11) NOT NULL DEFAULT '0' COMMENT '本车场费用',
  `vehicle_type` int(11) DEFAULT '1' COMMENT '车型：小车1，大车2，军警车65534',
  `power_type` int(11) DEFAULT '1' COMMENT '普通1，混合动力2，纯电动3',
  `logo` varchar(25) DEFAULT '未知' COMMENT '车标',
  `vehicle_model` int(11) DEFAULT '1' COMMENT '车运营类型',
  `body_color` int(11) DEFAULT '0' COMMENT '车身颜色',
  `in_taxprinted` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '已开具发票(0:未开,1:已开)',
  `taxprinted` tinyint(4) DEFAULT '0' COMMENT '已开具发票(0:未开,1:已开)',
  `now_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `out_time` (`out_time`),
  KEY `now_time` (`now_time`),
  KEY `plate` (`in_used_plate`),
  KEY `card` (`in_vpr_card`),
  KEY `trace_uk` (`trace_uk`) USING BTREE,
  KEY `in_time` (`in_time`)
) ENGINE=InnoDB AUTO_INCREMENT=133432 DEFAULT CHARSET=utf8;
